In [1]:
import numpy as np
import torch

In [218]:
# https://subinium.github.io/pytorch-Tensor-Variable/

<img src='img/tensor.png'/>

## Creating tensor

* fixed dtype constructor

In [35]:
t = torch.FloatTensor([1,2,3,4,5]) # torch.Tensor is alias for torch.FloatTensor
print(t, t.dtype)

tensor([1., 2., 3., 4., 5.]) torch.float32


* specifying dtype with torch.tensor

In [39]:
t = torch.tensor([1,2,3,4,5], dtype=torch.int32) # or could use torch.IntTensor
print(t)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


* empty tensor

In [49]:
torch.Tensor(2,3) # using fixed dtype constructor

tensor([[-4.0221e+35,  4.5778e-41,  5.2935e+08],
        [ 3.0904e-41,         nan,  0.0000e+00]])

In [50]:
torch.empty((2,4), dtype=torch.int32) # specify dtype

tensor([[1308390000,      22054, 1308257152],
        [     22054,          1,          0]], dtype=torch.int32)

* from numpy array

In [118]:
arr = np.random.rand(2,3)
print(arr.dtype)

# torch.tensor는 항상 copy를 함
t1 = torch.tensor(arr) # copy of arr
t2 = torch.from_numpy(arr) # share memory with arr

# dtype이 다른 생성자를 쓸 경우 copy 함
t3 = torch.FloatTensor(arr) # copy of arr
t4 = torch.DoubleTensor(arr) # share memory with arr

arr[0,0] = 3

print(t1)
print(t2)
print(t3)
print(t4)

float64
tensor([[0.3743, 0.8407, 0.1824],
        [0.4239, 0.2597, 0.8500]], dtype=torch.float64)
tensor([[3.0000, 0.8407, 0.1824],
        [0.4239, 0.2597, 0.8500]], dtype=torch.float64)
tensor([[0.3743, 0.8407, 0.1824],
        [0.4239, 0.2597, 0.8500]])
tensor([[3.0000, 0.8407, 0.1824],
        [0.4239, 0.2597, 0.8500]], dtype=torch.float64)


* ones / zeros

In [206]:
ones = torch.ones(3,4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [214]:
zeros = torch.zeros(2,5)
print(zeroes)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [217]:
torch.ones_like(zeros) # shape 뿐만 아니라 device도 모방함

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [216]:
torch.zeros_like(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Type casting

In [190]:
t = torch.Tensor([1,2,3])
print(t.dtype)

torch.float32


In [193]:
t.int() # t.float(), t.double(), ... => .to()에서 파생됨

tensor([1, 2, 3], dtype=torch.int32)

In [194]:
t.to(torch.int32) # 더 일반화된 버전, device도 바꿀 수 있음

tensor([1, 2, 3], dtype=torch.int32)

## Attributes of tensor

In [120]:
t = torch.Tensor([[1,2,3,4],[5,6,7,8]])

In [127]:
print('rank :', t.dim())
print('shape :', t.shape)  # shape, same as t.size()
print('number of elements :', t.numel())

rank : 2
shape : torch.Size([2, 4])
number of elementss : 8


## Matrix multiplication

* matrix multiplication
  * tensor.matmul
  * can be simplified to @

In [160]:
# vector x vector : 내적
tensor1 = torch.randint(-3, 3, (3,))
tensor2 = torch.randint(-3, 3, (3,))
print(tensor1, tensor2)
tensor1 @ tensor2

tensor([-1,  2,  0]) tensor([ 2, -1, -2])


tensor(-4)

In [141]:
# vector x matrix
tensor1 = torch.randint(-3, 3, (3,))
tensor2 = torch.randint(-3, 3, (3,2))
print(tensor1)
print(tensor2)
torch.matmul(tensor1, tensor2)

tensor([0, 1, 1])
tensor([[ 1,  1],
        [ 1, -1],
        [-3,  2]])


tensor([-2,  1])

In [142]:
# matrix x vector
tensor1 = torch.randint(-3, 3, (2,3))
tensor2 = torch.randint(-3, 3, (3,))
print(tensor1, tensor2)
torch.matmul(tensor1, tensor2)

tensor([[ 1, -3, -2],
        [ 0,  2, -2]]) tensor([-3,  1,  2])


tensor([-10,  -2])

In [144]:
# matrix x matrix
tensor1 = torch.randint(-3, 3, (2,3))
tensor2 = torch.randint(-3, 3, (3,2))
print(tensor1)
print(tensor2)
torch.matmul(tensor1, tensor2)

tensor([[-1,  1,  0],
        [ 2,  0, -1]])
tensor([[-2,  0],
        [ 0,  0],
        [-2, -1]])


tensor([[ 2,  0],
        [-2,  1]])

In [150]:
# batched matrix x broadcasted vector
tensor1 = torch.randint(-3, 3, (3, 2, 4))
tensor2 = torch.randint(-3, 3, (4,))
print(tensor1)
print(tensor2)
out = torch.matmul(tensor1, tensor2)
print(out)
print(tensor1.shape, tensor2.shape, out.shape)

tensor([[[ 0, -1, -3,  1],
         [-1, -1,  0,  0]],

        [[-1,  2, -2, -3],
         [ 0,  2, -2, -2]],

        [[ 1, -3,  0,  0],
         [ 0,  2,  1,  2]]])
tensor([-3,  0,  0, -3])
tensor([[-3,  3],
        [12,  6],
        [-3, -6]])
torch.Size([3, 2, 4]) torch.Size([4]) torch.Size([3, 2])


In [156]:
# batched matrix x batched matrix
tensor1 = torch.randint(-3, 3, (10, 7, 3, 4))
tensor2 = torch.randint(-3, 3, (10, 7, 4, 2))
out = torch.matmul(tensor1, tensor2)
print(tensor1.shape, tensor2.shape, out.shape)

torch.Size([10, 7, 3, 4]) torch.Size([10, 7, 4, 2]) torch.Size([10, 7, 3, 2])


In [162]:
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 17, 8, 3, 4)
tensor2 = torch.randn(8, 4, 5)
out = torch.matmul(tensor1, tensor2)
print(tensor1.shape, tensor2.shape, out.shape)

torch.Size([10, 17, 8, 3, 4]) torch.Size([8, 4, 5]) torch.Size([10, 17, 8, 3, 5])


* sum

In [168]:
tensor1 = torch.rand(2,3)
print(tensor1)
print(tensor1.sum())
print(tensor1.sum(dim=0))

tensor([[0.6058, 0.1385, 0.7620],
        [0.5414, 0.6441, 0.0289]])
tensor(2.7207)
tensor([1.1473, 0.7825, 0.7909])


* mean

In [169]:
tensor1 = torch.rand(2,3)
print(tensor1)
print(tensor1.mean())
print(tensor1.mean(dim=0))

tensor([[0.0698, 0.1095, 0.9531],
        [0.1867, 0.8605, 0.9056]])
tensor(0.5142)
tensor([0.1283, 0.4850, 0.9294])


* max

In [174]:
tensor1 = torch.rand(2,3)
print(tensor1)
print(tensor1.max())
print(tensor1.max(dim=0)) # also returns argmax

tensor([[0.4007, 0.8787, 0.8945],
        [0.1014, 0.1244, 0.4214]])
tensor(0.8945)
torch.return_types.max(
values=tensor([0.4007, 0.8787, 0.8945]),
indices=tensor([0, 0, 0]))


* argmax

In [172]:
tensor1 = torch.rand(2,3)
print(tensor1)
print(tensor1.argmax())
print(tensor1.argmax(dim=0))

tensor([[0.0418, 0.3779, 0.4596],
        [0.7039, 0.3551, 0.4305]])
tensor(3)
tensor([1, 0, 0])


## View operations

* view / reshape

In [175]:
t = torch.rand(12)
t

tensor([0.9416, 0.9754, 0.4000, 0.8737, 0.0241, 0.7994, 0.8812, 0.1809, 0.4543,
        0.6158, 0.9539, 0.9243])

In [180]:
t = t.view(3, 1, 4, 1) # t.reshape 도 가능하지만 reshape은 view와 다르게 항상 memory share를 보장하지 않음
t

tensor([[[[0.9416],
          [0.9754],
          [0.4000],
          [0.8737]]],


        [[[0.0241],
          [0.7994],
          [0.8812],
          [0.1809]]],


        [[[0.4543],
          [0.6158],
          [0.9539],
          [0.9243]]]])

* squeeze / unsqueeze

In [187]:
print(t.shape)
print(t.squeeze().shape)
print(t.squeeze(1).shape)
print(t.unsqueeze(0).shape)

torch.Size([3, 1, 4, 1])
torch.Size([3, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 1, 4, 1])


> transpose, permute, scatter, gather

## Merging operations

In [196]:
x = torch.FloatTensor([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
y = torch.FloatTensor([[5, 6, 7], [7, 8, 9], [9, 10, 11]])

* concatenate : reserve dimension

In [200]:
merged = torch.cat([x, y])
print(merged, merged.shape)

merged = torch.cat([x, y], dim = 1)
print(merged, merged.shape)

tensor([[ 1.,  2.,  3.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 5.,  6.,  7.],
        [ 7.,  8.,  9.],
        [ 9., 10., 11.]]) torch.Size([6, 3])
tensor([[ 1.,  2.,  3.,  5.,  6.,  7.],
        [ 3.,  4.,  5.,  7.,  8.,  9.],
        [ 6.,  7.,  8.,  9., 10., 11.]]) torch.Size([3, 6])


* stack : add dimension

In [201]:
merged = torch.stack([x,y])
print(merged, merged.shape)

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.],
         [ 9., 10., 11.]]]) torch.Size([2, 3, 3])


In [202]:
merged = torch.stack([x,y], dim=1)
print(merged, merged.shape)

tensor([[[ 1.,  2.,  3.],
         [ 5.,  6.,  7.]],

        [[ 3.,  4.,  5.],
         [ 7.,  8.,  9.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]]) torch.Size([3, 2, 3])
